### PR TITLE
Acceptance tests

### PR DESCRIPTION
**Pull request by SocksDevil**
Added acceptance tests for current profile page, friend requests and current listing of connected people

### CODE REVIEW

**Review by TitoGrine — DISMISSED** [review]
They all passed for me. It seems to be good to go.

**Review by diogosmac — DISMISSED** [review]
:ok_hand:

**Review by TitoGrine — APPROVED** [review]
The good stuff 💯

**Review by diogosmac — APPROVED** [review]
:lipstick: :fire:

**Pull request merged**
